[project]
name = "airbnb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apify-client>=2.5.0",
    "beautifulsoup4>=4.14.3",
    "requests>=2.32.5",
]
